language: python
python:
    - "3.5"
services:
    - redis-server
before_install:
    - pip install codecov
install:
    - pip install -r requirements.txt
notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/47fad412a43216dc3066
        on_success: always
        on_failure: always
        on_start: never
after_success:
    - codecov
script: python -m unittest -v unitTests.StoneworkUnits