language: python
python:
    - "3.5"
services:
    - redis-server
before_install:
    - pip install codecov
install:
    - pip install 'cython>=0.23.4' git+git://github.com/gevent/gevent.git#egg=gevent
    - pip install -r requirements.txt
notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/47fad412a43216dc3066
        on_success: always
        on_failure: always
        on_start: never
after_success:
    - codecov
script: coverage run -m unittest -v unitTests.StoneworkUnits